In [1]:
import numpy as np 
import pandas as pd

In [12]:
class svm():
    def __init__(self,learning_rate=0.01, lambda_param=0.01, n_iter = 1000):
        self.lr = learning_rate
        self.lambda_param = lambda_param
        self.iter = n_iter
        self.w = None
        self.b = None

    def fit(self,X_train,y_train):
        n_sample, n_features = X_train.shape

        y_ = np.where(y_train<=0, -1, 1)

        self.w = np.random.randn(n_features)
        self.b = 0

        for _ in range(self.iter):
            for idx, x_i in enumerate(X_train):
                condition = y_[idx]*(np.dot(x_i,self.w)- self.b) >= 1
                if condition :
                    self.w = self.w - self.lr*(2*self.lambda_param*self.w)
                else :
                    self.w =  self.w - self.lr*(2*self.lambda_param*self.w - np.dot(x_i,y_[idx])) 
                    self.b  = self.b - self.lr*(y_[idx])

    
    def predict(self,X_test):
        approx = np.dot(X_test,self.w) - self.b
        return np.sign(approx)



In [3]:
from sklearn.model_selection import train_test_split
from sklearn.datasets import make_blobs
import matplotlib.pyplot as plt
import seaborn as sns 

In [13]:
X,y = make_blobs(n_samples=100,n_features=2,centers=2,cluster_std=1.0,center_box=(-10.0, 10.0),random_state=42)
X,y

(array([[-2.98837186,  8.82862715],
        [ 5.72293008,  3.02697174],
        [-3.05358035,  9.12520872],
        [ 5.461939  ,  3.86996267],
        [ 4.86733877,  3.28031244],
        [-2.14780202, 10.55232269],
        [ 4.91656964,  2.80035293],
        [ 3.08921541,  2.04173266],
        [-2.90130578,  7.55077118],
        [-3.34841515,  8.70507375],
        [-2.44166942,  7.58953794],
        [ 3.40292813,  0.65271307],
        [-2.97867201,  9.55684617],
        [-3.83738367,  9.21114736],
        [ 3.95985411,  2.20542338],
        [ 3.85662554,  1.65110817],
        [ 4.70010905,  4.4364118 ],
        [ 3.56898634,  2.4556421 ],
        [ 4.69808755,  0.83019939],
        [-2.41743685,  7.02671721],
        [ 4.85397258,  0.72743091],
        [ 4.44751787,  2.27471703],
        [ 5.43091078,  1.06378223],
        [ 5.60325497,  2.38595061],
        [ 4.89976163,  2.75499256],
        [-0.92998481,  9.78172086],
        [ 4.56277713,  2.31432166],
        [-1.6966718 , 10.370

In [14]:
y

array([0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1,
       1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0])

In [15]:
y_ = np.where(y>=1,1,-1)

In [16]:
y_

array([-1,  1, -1,  1,  1, -1,  1,  1, -1, -1, -1,  1, -1, -1,  1,  1,  1,
        1,  1, -1,  1,  1,  1,  1,  1, -1,  1, -1,  1,  1, -1, -1, -1, -1,
       -1,  1,  1, -1, -1, -1, -1,  1,  1,  1,  1, -1, -1, -1, -1,  1,  1,
       -1, -1,  1, -1,  1, -1,  1,  1, -1, -1,  1, -1,  1,  1,  1,  1, -1,
        1,  1, -1,  1,  1,  1,  1,  1,  1, -1,  1, -1,  1, -1, -1, -1,  1,
       -1, -1, -1,  1, -1,  1, -1, -1, -1, -1, -1, -1,  1, -1, -1])

In [17]:
X_train, X_test, y_train, y_test = train_test_split(X, y_, test_size=0.20, random_state=42)
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((80, 2), (20, 2), (80,), (20,))

In [18]:
svm_ = svm()
svm_

In [19]:
svm_.fit(X_train,y_train)

In [20]:
y_predict = svm_.predict(X_test)
y_predict

array([-1.,  1., -1., -1.,  1., -1.,  1.,  1., -1., -1.,  1., -1.,  1.,
       -1.,  1.,  1.,  1., -1., -1., -1.])

In [21]:
y_test

array([-1,  1, -1, -1,  1, -1,  1,  1, -1, -1,  1, -1,  1, -1,  1,  1,  1,
       -1, -1, -1])

In [22]:
from sklearn.metrics import accuracy_score

In [23]:
accuracy_score(y_predict,y_test)

1.0

In [24]:
accuracy_score(y_test, y_predict)

1.0